### ISSUE TITLE
Document about size of batches, computing resources needed, and limitations of uploads

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/nda-bids-upload#8]
See title.

**Comment by ericearl** [comment]
Include disk space usage and estimated upload times.

**Comment by ericearl** [comment]
@rosemccollum I looked in the docs, but did not see where you made these changes? Could you reference the docs or the commit where you fixed this?

**Comment by rosemccollum** [comment]
We have the limitations of uploads/batch size here https://ndabids.readthedocs.io/en/latest/nda/ and there is an example sbatch in the utilities folder that has the recommended computing resources. Since that is an MSI specific sbatch, we are not specifically mentioning the resources in the documentation and are instead going to be documenting that on our lab readthedocs, at least that is my understanding, @audreymhoughton can correct me if I am mistaken.

**Comment by audreymhoughton** [comment]
@rosemccollum it might be worth giving a recommendation based on our experiences uploading, but I think that is the most we should add here.

**Comment by LuciMoore** [comment]
repo is no longer being maintained!
